name: Build & Deploy Documentation
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - run: poetry install --with=doc
      - run: poetry run mkdocs gh-deploy --force
